version: '3'
services:
  tilesbuilder:
    build: .
    links:
      - postgres-osm:pg
    volumes:
      - ~/osm:/data
      - ~/osm/conf:/conf
      - ~/osm/styles:/styles
      - docs-volume:/usr/share/nginx/html
    depends_on:
      - postgres-osm

  tileserver:
    image: "klokantech/tileserver-gl"
    volumes:
      - ~/osm:/data
      - ~/osm/conf:/conf
      - ~/osm/styles:/styles
    command: -c /conf/config.json
    ports:
      - "8080:80"
    depends_on:
      - "tilesbuilder"

  docs:
    build: ./docs
    ports:
      - 9090:80

  postgres-osm:
    image: "openfirmware/postgres-osm"
    ports:
      - 25432:5432

  maputnik:
    build: .
    volumes:
      - ~/osm/styles:/styles
    entrypoint: /maputnik/maputnik_linux
    command: --watch --file /styles/basic.json
    ports:
      - 9000:8000

volumes:
  docs-volume: