version: '3'
services:
  contour-tiles:
    build: .
    image: joeakeem/contour-tiles
    volumes:
      - ./osm:/data
    depends_on:
      - postgres-osm
    environment:
      DESCRIPTION: "Europe contour lines vector data by singletrail-map.eu"
      ATTRIBUTION: "©singletrail-map.eu ©OpenStreetMap"
      MIN_X: 34
      MAX_X: 43
      MIN_Y: 01
      MAX_Y: 05
      MIN_Z: 0
      MAX_Z: 5000
      CONTOUR_JOBS: 8
      GDAL_CACHEMAX: 16000

  postgres-osm:
    image: kartoza/postgis:15-3.3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      ALLOW_IP_RANGE: "0.0.0.0/0"
      POSTGRES_USER: "contour"
      POSTGRES_PASS: "passwd"
