version: '3'
services:
  contour-tiles:
    build: .
    image: joeakeem/contour-tiles
    volumes:
      - ./osm:/data
    depends_on:
      - postgres-osm
    environment:
      DESCRIPTION: "Europe contour lines vector data by singletrail-map.eu"
      ATTRIBUTION: "©singletrail-map.eu ©OpenStreetMap"

  postgres-osm:
    image: kartoza/postgis:15-3.3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      ALLOW_IP_RANGE: "0.0.0.0/0"
      POSTGRES_USER: "contour"
      POSTGRES_PASS: "passwd"
