version: '3'
services:
  tilesbuilder:
    build: tiles-builder
    image: joeakeem/tiles-builder
    links:
      - postgres-osm:pg
    volumes:
      - ~/osm:/data
    depends_on:
      - postgres-osm

  postgres-osm:
    image: openfirmware/postgres-osm
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data