version: '3'
services:
  tileserver:
    build: tiles-server
    image: joeakeem/tiles-server
    volumes:
      - ~/osm:/data
    command: "-c /config/config.json"
    ports:
      - 8080:80
    networks:
      - tileserver-net

  maputnik:
    build: tiles-server
    image: joeakeem/tiles-server
    entrypoint: /maputnik/maputnik_linux
    command: --watch --file /styles/basic.json
    ports:
      - 9000:8000
    networks:
      - tileserver-net

  docs:
    build: tiles-docs
    image: joeakeem/tiles-doc
    ports:
      - 9090:80
    networks:
      - tileserver-net

networks:
  tileserver-net:
    driver: bridge