version: '3'
services:
  contour-tileserver:
    image: klokantech/tileserver-gl:v2.6.0
    ports:
      - 8080:80
    volumes:
      - ./osm:/data
      - ./config:/config
    command: "-c /config/tileserver-config.json"